### ISSUE TITLE
All models for Windows downloading to `C:\Users\%username%\AppData\Local\nomic.ai\GPT4All`

### ISSUE THREAD

**Issue by darrylhansen** [nomic-ai/gpt4all-chat#101]
It would be much appreciated if we could modify this storage location for those of us that want to download all the models, but have limited room on C:.

Amazing work and thank you!

**Comment by apage43** [comment]
as a workaround for now, if you move them to the same folder as `chat.exe` (I'm assuming you've installed to a different drive) they should still show up in the model picker dropdown

**Comment by daemonk72** [comment]
You can use the symlink
Create a GPT4 folder on a spare drive, and place the symlink in the folder C:\Users\%username%\AppData\Local\nomic.ai\

**Comment by manyoso** [comment]
Fixed in latest release.
