### ISSUE TITLE
Issue downloading models - ubuntu 22.04

### ISSUE THREAD

**Issue by DrGood01** [nomic-ai/gpt4all-chat#103]
hello,

Jazzy was running very well. Now did a fresh install, check updates, start downloading vicuna. At the end, nothing happens, no model file in the specified directory .local/share/noamic/gpat4all. UI stays stucked to proposing to download models, since it cannot find any model in the above location or ~/GPT4ALL/bin.

thanks!

**Comment by DrGood01** [comment]
btw could you post here the urls pointing to the models that worked for you? Is that Vicuna? thanks!

**Comment by manyoso** [comment]
https://github.com/nomic-ai/gpt4all-chat#manual-download-of-models
