### ISSUE TITLE
 Unintended prompt submission when switching to another application/switching focus away from the GPT4All application window

### ISSUE THREAD

**Issue by Silentoplayz** [nomic-ai/gpt4all-chat#105]
# Description
There is a bug I've personally found in the GPT4All application after only a few minutes of use that causes prompt messages to be automatically sent to the AI for processing, even if the user hasn't explicitly initiated the action by using the paper airplane button to send the message or by pressing `Enter` on their device's keyboard. This problem has been observed to occur when the GPT4All application window loses focus, such as when the user switches to another application, opens the Windows menu, or clicks anywhere outside the application window.

# Steps to reproduce
1. Launch the GPT4All application.
2. Enter a prompt in the input field, but do not initiate sending it to the AI for processing.
3. Click on the Task Manager to check the computer's CPU and RAM usage, switch to any other application on the PC, or click anywhere outside the GPT4All application window.
4. Notice that the prompt has been automatically sent to the AI for processing.

# Expected behavior
The prompt message should only be sent to the AI for processing when the user explicitly initiates the action.

# Actual behavior
When the GPT4All application window loses focus, the prompt message is automatically sent to the AI for processing.

# Environment
- **GPT4All application version**: v2.2.2
- **Edition**: Windows 11 Pro
- **Version**: 22H2
- **OS build**: 22621.1555
- **Experience**: Windows Feature Experience Pack 1000.22640.1000.0

# Additional information
This bug has been tested and confirmed to occur in several scenarios, including:
- Switching to both running and non-running applications on the PC.
- Opening the Windows menu from the taskbar.
- Clicking anywhere outside the GPT4All application window.

Please investigate this issue and provide a fix to prevent unintended prompt submissions in the GPT4All application.

**Comment by manyoso** [comment]
Fixed.
