### ISSUE TITLE
Regenerate Response Button Issues in Empty Conversations

### ISSUE THREAD

**Issue by Silentoplayz** [nomic-ai/gpt4all-chat#106]
# Issue Description:
In the GPT4All application, the `Regenerate Response` button does not function as expected when interacting with empty conversations and changing AI models.

# Steps to Reproduce:
1. Open the GPT4All application.
2. Ensure there is an empty conversation with any AI model.
3. Observe that the `Regenerate Response` button is already being shown to you, even in an empty conversation without any messages having been sent by the user or an AI model.
4. Press the `Regenerate Response` button and observe no visual response.
5. Change the AI model in the application header and observe the `Regenerate Response` button does not disappear.
6. Press the `Refresh` button in the application header and observe that it does not remove the `Regenerate Response` button after clearing a conversation with messages.

# Expected Behavior:
1. The `Regenerate Response` button should only be active and responsive when there is a message in the conversation produced by an AI model to regenerate.
2. The `Regenerate Response` button should disappear when changing the AI model or clearing a conversation with the `Refresh` button.

# Actual Behavior:
1. The `Regenerate Response` button does not visually respond when clicked in an empty conversation with any AI model.
2. Changing the AI model in the application header does not remove the `Regenerate Response` button.
3. Pressing the `Refresh` button in the application header does not remove the `Regenerate Response` button, even when clearing out a conversation with messages in it already.
4. The `Refresh` button appears grayed out and does not function in an empty conversation (which might actually be expected or intended behavior).

# Environment:
**Application**: GPT4All v2.2.2
## OS:
- **Edition**: Windows 11 Pro
- **Version**: 22H2
- **OS build**: 22621.1555
- **Experience**: Windows Feature Experience Pack 1000.22640.1000.0

# Additional Information:
This issue may cause confusion for users who might expect the Regenerate Response button to function in empty conversations, or when changing AI models. Resolving this issue will improve the overall user experience and make the application more intuitive.

**Comment by manyoso** [comment]
Fixed with 73715075c9fca6f932d744efc0097d1c45e10957 and thank you again for the amazing bug report!
