### ISSUE TITLE
Why can't I download the bin file?

### ISSUE THREAD

**Issue by Burgeon0110** [nomic-ai/gpt4all-chat#108]
This is the new version. But I can't download the bin file.
![image](https://user-images.githubusercontent.com/128889876/234415696-7aa12d51-3ba5-437e-a36d-f0556f5a172c.png)

**Comment by manyoso** [comment]
What is happening? Looks like a slow connection

**Comment by Burgeon0110** [comment]
Firstly, I have a high-speed network here. If it's a low-speed connection you mentioned, is there any way to solve it?

**Comment by Burgeon0110** [comment]
Does your program have breakpoint continuation function?

**Comment by Burgeon0110** [comment]
I know your program can run on my other computers, which are all newly configured.

**Comment by Burgeon0110** [comment]
错误模块路径: E:\gpt4all\bin\libllama.dll
![f3b11475ef09bbdfcd47809fc0e387f](https://user-images.githubusercontent.com/128889876/234466093-7ce133a1-e967-4dc8-b265-b217f6c325d7.png)

**Comment by manyoso** [comment]
https://github.com/nomic-ai/gpt4all-chat#manual-download-of-models
