### ISSUE TITLE
Cannot retrieve remote tree. - Windows (networking issue with installer)

### ISSUE THREAD

**Issue by Shivanandroy** [nomic-ai/gpt4all-chat#11]
![image](https://user-images.githubusercontent.com/25221992/231967130-2f266b31-f205-43b5-b977-bd2d05b34fb5.png)

**Comment by manyoso** [comment]
Could be a proxy, firewall, dns issue... could you try and disable firewall or setup proxy?

**Comment by manyoso** [comment]
This is def. on the client side. Closing.
