### ISSUE TITLE
Improve LLmodel prompt context handling

### ISSUE THREAD

**Issue by kuvaus** [nomic-ai/gpt4all-chat#117]
## Description:

In the previous version of the LLmodel library, the prompt handling function signature only took `std::string &prompt`, a `response function`, and a `PromptContext &ctx`. The new version has introduced a `recalculate function`, and the updated function signature includes `std::string &prompt`, a `response function`, a `recalculate function`, and a `PromptContext &ctx`.

However, the handling of the PromptContext and tokens has also changed, and it could benefit from being cleaned up and simplified to improve the user experience when working with the LLmodel library.

```c++
void prompt(const std::string &prompt, ResponseFunction response,
            PromptContext &ctx, int32_t n_predict = 200, int32_t top_k = 50400,
            float top_p = 1.0f, float temp = 0.0f, int32_t n_batch = 9);

void prompt(const std::string &prompt, ResponseFunction response,
                    RecalculateFunction recalculate, PromptContext &ctx);
```
## Suggestion:

Improve the handling of the PromptContext (&ctx) and tokens by cleaning up the code and simplifying its usage, making it more accessible for end-users of the LLmodel library.

**Comment by manyoso** [comment]
Thanks, will do this.

**Comment by manyoso** [comment]
Done
