### ISSUE TITLE
Missing model after install? bash: ./bin/gpt-j: No such file or directory

### ISSUE THREAD

**Issue by TheMemeticist** [nomic-ai/gpt4all-chat#118]
When I try to run: ./bin/gpt-j -m ggml-gpt4all-j-v1.2-jazzy.bin -n 200 --top_k 40 --top_p 0.9 -b 9 --temp 0.9 -p "Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Tell me about artifical intelligence
### Response:"

I get : bash: ./bin/gpt-j: No such file or directory

Do I need to download the model separately?

**Comment by manyoso** [comment]
There is no ./bin/gpt-j built by this repo
