### ISSUE TITLE
Intel MacOS: Bad CPU type

### ISSUE THREAD

**Issue by RedWideWeb** [nomic-ai/gpt4all-chat#12]
Is it possible to make the version of GPT4ALL installer for Intel Macs and for macOS 10.13?

It is great to have an option to update all components from one place.

**Comment by manyoso** [comment]
We're aware and trying to make a universal binary. Thanks for reporting!

**Comment by RedWideWeb** [comment]
@manyoso Thank you very much!

**Comment by RedWideWeb** [comment]
@manyoso will you also please make it compatible with pre 11 macOS versions. At least High Sierra as it is still used and many apps still work on it.

**Comment by manyoso** [comment]
other reports already so removing duplicates but thanks for reporting
