### ISSUE TITLE
Model download screen should highlight recommended models for download

### ISSUE THREAD

**Issue by AndriyMulyar** [nomic-ai/gpt4all-chat#120]
Some users in the discord report confusion around which model they should use.

I propose we somehow emphasize the two best models from the list. I think we should always emphasize the **best** Apache 2 model and then the **best** non-Apache 2 model.

**Comment by manyoso** [comment]
I was thinking of adding a description field somehow and including that in the json too...

Right now, the only thing I tag is groovy with (default)

**Comment by AndriyMulyar** [comment]
We're basically replicating model cards you'd find on huggingface.
Something to think about. But yeah
- descriptions
- license

Are all useful attributes.

**Comment by manyoso** [comment]
We could make the huggingface the place where these models are downloaded from...
