### ISSUE TITLE
Building and running CLI tools only (no Qt required)

### ISSUE THREAD

**Issue by chongy076** [nomic-ai/gpt4all-chat#125]
Hi ,

first it is looking for ggml folder in your instruction 
cd gpt4all-chat/ggml , i believe this would need to compiled from ggml git at the top.

when compiling ggml on lenovo p53 Ram 32 and installed https://cmake.org/install/ , error as below appeared.

-------------------------------------------------------------------------------
(base) C:\share\gpt4all-chat\ggml\build>cmake --build . --parallel
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/share/gpt4all-chat/ggml/examples/CMakeLists.txt
  Building Custom Rule C:/share/gpt4all-chat/ggml/src/CMakeLists.txt
  common.cpp
cl : Command line warning D9002: ignoring unknown option '-mfma' [C:\share\gpt4all-chat\ggml\build\src\ggml.vcxproj]
  ggml.c
cl : Command line warning D9002: ignoring unknown option '-mf16c' [C:\share\gpt4all-chat\ggml\build\src\ggml.vcxproj]
cl : Command line warning D9002: ignoring unknown option '-mavx' [C:\share\gpt4all-chat\ggml\build\src\ggml.vcxproj]
cl : Command line warning D9002: ignoring unknown option '-mavx2' [C:\share\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(875): error C2146: syntax error: missing ')' before identifier 'x' [C:\s
hare\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(875): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\g
gml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(875): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(875): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(875): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(876): error C2146: syntax error: missing ')' before identifier 'x' [C:\s
hare\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(876): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\g
gml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(876): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(876): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(876): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(877): error C2146: syntax error: missing ')' before identifier 's' [C:\s
hare\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(877): error C2061: syntax error: identifier 's' [C:\share\gpt4all-chat\g
gml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(877): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(877): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(877): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(880): error C2061: syntax error: identifier 'dequantize_row_q_t' [C:\sha
re\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(881): error C2061: syntax error: identifier 'quantize_row_q' [C:\share\g
pt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(881): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(882): error C2061: syntax error: identifier 'quantize_row_q_reference' [
C:\share\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(882): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(883): error C2061: syntax error: identifier 'quantize_row_q_dot' [C:\sha
re\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(883): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(884): error C2061: syntax error: identifier 'vec_dot_q' [C:\share\gpt4al
l-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(884): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(886): error C2059: syntax error: '}' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(888): error C2061: syntax error: identifier 'ggml_internal_get_quantize_
fn' [C:\share\gpt4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(888): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\s
rc\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\include\ggml\ggml.h(888): error C2059: syntax error: '<parameter-list>' [C:\share\gpt4all-ch
at\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(401): warning C4244: 'argument': conversion from 'uint64_t' to 'const un
signed int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(406): warning C4244: 'argument': conversion from 'const uint64_t' to 'co
nst unsigned int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(409): warning C4244: 'argument': conversion from 'uint64_t' to 'const un
signed int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(413): warning C4244: 'argument': conversion from 'uint64_t' to 'const un
signed int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(421): warning C4244: 'argument': conversion from 'const uint64_t' to 'co
nst unsigned int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(422): warning C4244: 'argument': conversion from 'const uint64_t' to 'co
nst unsigned int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(424): warning C4244: 'argument': conversion from 'uint64_t' to 'const un
signed int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(425): warning C4244: 'argument': conversion from 'uint64_t' to 'const un
signed int', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(433): warning C4244: 'initializing': conversion from 'double' to 'float'
, possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(433): warning C4244: 'initializing': conversion from 'double' to 'const
float', possible loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\examples\common.cpp(455): warning C4244: 'argument': conversion from 'int' to 'float', possi
ble loss of data [C:\share\gpt4all-chat\ggml\build\examples\common.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(737): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt4
all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(737): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\build
\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(737): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.v
cxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(737): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.v
cxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(737): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.v
cxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(777): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt4
all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(777): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\build
\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(777): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.v
cxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(777): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.v
cxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(777): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.v
cxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1081): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1081): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1081): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1081): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1081): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1122): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1122): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1122): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1122): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1122): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1246): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1246): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1246): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1246): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1246): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1284): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1284): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1284): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1284): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1284): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1292): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1292): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1292): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1292): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1292): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1327): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1327): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1327): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1327): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1327): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1335): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1335): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1335): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1335): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1335): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1376): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1376): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1376): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1376): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1376): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1384): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1384): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1384): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1384): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1384): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1424): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1424): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1424): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1424): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1424): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1433): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1433): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1433): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1433): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1433): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1458): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1458): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1458): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1458): error C2059: syntax error: ',' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1458): error C2059: syntax error: ')' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1467): error C2146: syntax error: missing ')' before identifier 'x' [C:\share\gpt
4all-chat\ggml\build\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1467): error C2061: syntax error: identifier 'x' [C:\share\gpt4all-chat\ggml\buil
d\src\ggml.vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1467): error C2059: syntax error: ';' [C:\share\gpt4all-chat\ggml\build\src\ggml.
vcxproj]
C:\share\gpt4all-chat\ggml\src\ggml.c(1467): fatal error C1003: error count exceeds 100; stopping compilation [C:\share
\gpt4all-chat\ggml\build\src\ggml.vcxproj]
  common.vcxproj -> C:\share\gpt4all-chat\ggml\build\examples\Debug\common.lib
------------------------------------------------------------------------------------------------------------

2. for no QT , it is asking for QT
 git clone --recurse-submodules https://github.com/nomic-ai/gpt4all-chat
cd gpt4all-chat/ggml
mkdir build
cd build
cmake ..

 C:\share\gpt4all-chat\build>cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19044.
-- The CXX compiler identification is MSVC 19.16.27038.0
-- The C compiler identification is MSVC 19.16.27038.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/WDExpress/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/WDExpress/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:38 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" (requested
  version 6.2) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

Thanks

**Comment by manyoso** [comment]
This can't be the case anymore as that submodule was deleted. Run 'git submodule update --init --recursive'
