### ISSUE TITLE
Installation on Fedora 37 (SOLVED!)

### ISSUE THREAD

**Issue by morpheus2448** [nomic-ai/gpt4all-chat#14]
After download and install of version 0.1.0 I ran into some issues.

`./chat: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`

I tried installing libjpeg-turbo-devel but that did not help. After some searching I ran the following commands which fixes the error:

`sudo dnf copr enable aflyhorse/libjpeg && sudo dnf install libjpeg8`

I run the chat app again:

`./chat: error while loading shared libraries: libxcb-cursor.so.0: cannot open shared object file: No such file or directory`

To fix this error I ran:

`sudo dnf install xcb-util-cursor`

Success!

```
./chat 
QML debugging is enabled. Only use this in a safe environment.
gptj_model_load: loading model from 'ggml-gpt4all-j.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: memory_size =  1792.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
```

It took a minute to load and my whole screen froze while it did so, but after my browser with many tabs open crashed; the chat window opened.

Hope this is helpful.

**Comment by manyoso** [comment]
Very helpful, thanks!

**Comment by Gabriel-Alves-Cunha** [comment]
Thank u god :pray:

**Comment by manyoso** [comment]
Done. Installer now give these shared libs.
