### ISSUE TITLE
INTEL Mac problem... MacOS: Bin does not run on this system (intel mac not supported yet)

### ISSUE THREAD

**Issue by flutterrausch** [nomic-ai/gpt4all-chat#15]
Installer successful, generated Applications/gpt4all/bin/gpt4all.app "does not run on system":

16" MacbookPro 2019 (Intel i7)
Ventura 13.2.1

I guess it only runs on M1/M2?

Names of files and error message are similar from what I remember (already deleted everything).

**Comment by afloch2000** [comment]
Yes I have the same issue. Could someone confirm the HW requirements for Mac?

**Comment by manyoso** [comment]
Confirmed that the installer doesn't support Intel macs yet. Actively working on it.

**Comment by flutterrausch** [comment]
Please note on the download, it's 3GB ;-)

**Comment by manyoso** [comment]
Closing as this is duplicate of another one and almost solved.

**Comment by flutterrausch** [comment]
Um. Is it solved or not? When? Neither download, nor other tickets give a hint.
