### ISSUE TITLE
 The application requires macOS 12.5 or later.

### ISSUE THREAD

**Issue by murchie85** [nomic-ai/gpt4all-chat#2]
Will you be adding earlier compatibility?

**Comment by manyoso** [comment]
I'd need an earlier mac to compile it with. How much earlier are we talking?

**Comment by murchie85** [comment]
Ah, my version is 12.2.1. Is there another way if this isn't possible?

**Comment by drscotthawley** [comment]
Thanks for posting this Issue. I was getting an error message on 12.3 that this application was incompatible with my OS and I couldn't figure out why, since I followed the Mac Install instructions correctly.  (It didn't tell me I needed to update my OS, just that the version was incompatible.)

**Comment by cyrillic** [comment]
It won't open on my 2017 MacBook Pro even though I'm running Ventura 13.2.1.
Maybe it'd need to be compiled for Intel Macs?

**Comment by Nsabatier** [comment]
> It won't open on my 2017 MacBook Pro even though I'm running Ventura 13.2.1. Maybe it'd need to be compiled for Intel Macs? (I meant the installer, I'll try compiling it myself)

The chat.app seems to be compiled for Apple Silicon (right-click > information on the chat.app). Too bad as I have an Intel Mac...

**Comment by murchie85** [comment]
So...still far from gpt4all

**Comment by gtgthub** [comment]
I can't open chat.app on MacOS Catalina 10.15. Will you ever make it backward compatible? It'd be great. Thanks

**Comment by manyoso** [comment]
This is going to be solved imminently and i have other issues to track it so closing this one for now.
