### ISSUE TITLE
Download keeps failing during installation

### ISSUE THREAD

**Issue by micnetix** [nomic-ai/gpt4all-chat#21]
Is there a way to install via downloading the 0,1.0bin.7z file with download manager because i have tried for hours now to do the installer but is stops downloading and starts over again.

**Comment by gmy77** [comment]
Happen to me the first time i install... connection broken and re-start from beginning. The second time i try i leave ONLY the program to download and i not use any other... like the first try i view on YouTube etc... and the second try work.

**Comment by manyoso** [comment]
Sounds like a networking problem... is it your side dropping the connection or is it the server side? If it is client side, nothing we can do, but if you can confirm it is server side we would like to know and fix

**Comment by micnetix** [comment]
its the server dropping the connnection it also drops when dirrectly downloading the 0,1,0bin with download manager but it allows to resume unlike the installer app just goes back to beginning

**Comment by micnetix** [comment]
i got the app to work from the 0.1.0bin.7z but no icon no shortcuts and no update feature.

**Comment by micnetix** [comment]
they should have made it one installer with all the files with it instead of trying to connect to internet and download large files or they can add resume capability. But if its one complete installer they can also upload to torrent so people can have a far better way to get these large files

**Comment by micnetix** [comment]
![Screenshot 2023-04-14 214532](https://user-images.githubusercontent.com/103886843/232061075-9f3874b2-5d57-4159-b1a0-51f5ce4f4073.png)
![Screenshot 2023-04-14 214609](https://user-images.githubusercontent.com/103886843/232061099-ddaf9e76-6ada-4209-a4da-dbc6577a5bde.png)

**Comment by micnetix** [comment]
its like clockwork soon as it gets to about 1500MB server drops the connection it does the same downloading dirrect from https://gpt4all.io/installer_repos/windows/repository/gpt4all/0.1.0bin.7z with a download manager. Server seams to time out and drop out.

**Comment by IanMcRV** [comment]
Same here its downloading about half of the 3gig then it errors and I have to start all over again.
Most frustrating!

**Comment by micnetix** [comment]
yes i have tried multiple computers and connections and same for all about half and server times out

**Comment by micnetix** [comment]
Yeah this is getting me absolutely nowhere i give up on ever getting the installation app to ever download the 0.1.0bin.7z file. Just download the file direct using chrome of a download manager https://gpt4all.io/installer_repos/windows/repository/gpt4all/0.1.0bin.7z extract if to where ever you want double click the chat.exe and boom it runs everything works but updates and there is no shortcut and icon for the shortcut but you can make you own. Anything is better than the installer its complete trash and has no resume.

**Comment by micnetix** [comment]
here is the icon so you can make the shortcut https://github.com/nomic-ai/gpt4all-chat/raw/master/icons/favicon.ico

**Comment by pavlass2** [comment]
Same problem here. To me it also seemed to close the connection always at the same time. I tried it like 3 times. Then I downloaded manually as @micnetix suggested. That's a good and easy workaround if you experience this.

**Comment by manyoso** [comment]
This is a client side issue. closing.
