### ISSUE TITLE
Unable to install on MacOS (WORKAROUND AVAILABLE!)

### ISSUE THREAD

**Issue by Alex-NY** [nomic-ai/gpt4all-chat#213]
Getting an error message:
“gpt4all-installer-darwin” cannot be opened because the developer cannot be verified.
Is there a way to circumvent this?

**Comment by Critical11** [comment]
> Getting an error message: “gpt4all-installer-darwin” cannot be opened because the developer cannot be verified. Is there a way to circumvent this?

Right click- Open

**Comment by Alex-NY** [comment]
MacBook Pro, Intel i5, 16G/1T, Ventura 13.3.1
