### ISSUE TITLE
Model-downloads are constantly breaking (WORKAROUND AVAILABLE!)

### ISSUE THREAD

**Issue by KiBLS** [nomic-ai/gpt4all-chat#218]
When I try to download new models the downloads abort all the time without an error message. I just can try to start the download again...

But I always get these error messages inside the terminal;

qt.network.http2: stream 9 finished with error: "Internal server error"
ERROR: downloading: "Internal server error"
qt.network.http2: stream 3 finished with error: "Internal server error"
ERROR: downloading: "Internal server error"

But my internet connection is ok and working all the time. I have no outages or disconnections at all. I have this issue now since I am using (or try to use) gpt4all. 

By pure chance, I was able to download the standard model a few days ago now, but that's all I've managed so far. What might be the reason for this? Are your servers too slow? Are there too many downloads or what can I change to download all models? I even tried to download the models at night with the same negative results.

Or is there maybe any verified, external source at Github (or similar sites) where I can download the models individually to put them manually into the folder /home/user/.local/share/nomic.ai/GPT4All/? Because I have no problem with downloading files through my browser, only with gpt4all this problem occurs somehow. 

Thanks for help and support in advance and best regards from germany!

**Comment by manyoso** [comment]
https://github.com/nomic-ai/gpt4all-chat/blob/master/README.md#manual-download-of-models

Just added the above. Sorry, I don't know what is going on with model downloads failing for some people ^^^. Hopefully that mitigates the issue or provides a workaround.

**Comment by KiBLS** [comment]
Strange, also these downloads are aborted several times but I could finish them successfully because I can continue interrupted downloads in firefox. 

So the links were helpful, thank you very much!
