### ISSUE TITLE
Why is User Interface not released under the same Apache 2 license?

### ISSUE THREAD

**Issue by BoQsc** [nomic-ai/gpt4all-chat#22]
https://github.com/manyoso/gpt4all-chat#license

> **The source code of this chat interface is currently under a GPL license.** 
> The underlying GPT4All-j model is released under non-restrictive open-source Apache 2 License.

**Comment by manyoso** [comment]
It may well be in future.

**Comment by manyoso** [comment]
It is now under MIT license which is compatible with Qt. Apache 2.0 is not.
