### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by SC-Elizabeth** [nomic-ai/gpt4all-chat#247]
Running windows 11 Pro. Followed instructions exactly but not familiar with the tools.

Upon reaching the build section and using the "cmake .." command, i encounter an error:

`CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!`

**Comment by manyoso** [comment]
Unfortunately, it is a little more complicated. You're running into this because it is trying to use the msvc compiler and not mingw64. I'll see if I can come up with a more thorough build walk through with screenshots for the future.

**Comment by SC-Elizabeth** [comment]
Aw, sorry. I thought i have properly installed mingw64 during the qt installation
