### ISSUE TITLE
Readme (or related usage policy document) should state outright if  content intended for mature audiences, or in sensitive areas can be generated.

### ISSUE THREAD

**Issue by afarlie** [nomic-ai/gpt4all-chat#25]
(In followup to Issue #4 )
In clarification and, for the avoidance of any doubt, the read-me and associated documentation, should indicate if  mature, explicit or NSFW content can or cannot be generated with the model/toolset, provided that the content (or generation thereof) does not constitute a breach of appropriate legal or regulatory requirements in a given users jurisdiction or region. (You might also add applicable community standards here, but those can vary quite considerably.)

As well as above ideally, the read-me (or a separate ethical use policy document) should indicate if certain sensitive areas are allowed or disallowed. (The recent update made effectively already gives the " Don't use this for illegal or unethical things." line in most typical usage policy.)

 Some sample areas of potential concern follow (this is not an exhaustive list.):-
*Content which contains overt political or ideological content,  or which is intended to inform/influence the views or choices of a potential (competent) reader,  on issues of public concern, or in an election. (Examples being  campaign material, lobbying briefings or public service announcement "fillers".)
*The use of fictionalized representations of potentially identifiable individuals (living or deceased), corporations (both current and defunct) and prominent brands , franchises or trademarks associated with those individuals or corporations.
*Content which contains LGBTQI themes, including cross-dressing or explorations of non-binary and gender-fluid presentation.
*Content which whilst not containing (explicit) deceptions of actual sexual activity, may explore alternative sexuality, fetishes, or practices of a mutually consensual nature, between informed consenting adult participants. 
*Use of profanity and pejoratives. (in an appropriate context)
*Deceptions of violence, crime, 'abuse' or self-harm.  (in line with the editorial standards typically applied in print or other media.)
*Professional advice which would typically be made a qualified individual under regulatory supervision (such as Doctors, attorneys, financial advisers, architects and engineers, )

I know that this may seem to be overly cautious, but it would seem reasonable to have some kind of guidance document, beyond the typical "Do not do illegal, immoral or crazy things  with this.."  common in most open-source projects. Especially given that LLM's are getting media attention.

**Comment by gmy77** [comment]
True... in this "new world" good to write few words more than problems... later.

**Comment by Rhialto** [comment]
I see a problem where somebody (or some reactionary group) wants to enforce its own morals, and tries to prevent discussion of things like the mentioned "LGBTQI themes, including cross-dressing or explorations of non-binary and gender-fluid presentation" or "alternative sexuality, fetishes, or practices of a mutually consensual nature, between informed consenting adult participants" or so-called "profanities", etc etc...

**Comment by afarlie** [comment]
> I see a problem where somebody (or some reactionary group) wants to enforce its own morals, and tries to prevent discussion of things like the mentioned "LGBTQI themes, including cross-dressing or explorations of non-binary and gender-fluid presentation" or "alternative sexuality, fetishes, or practices of a mutually consensual nature, between informed consenting adult participants" or so-called "profanities", etc etc...

Which is why a model which is aiming to be 'free' (GNU sense) ideally needs to say upfront it's not going to impose usage restrictions on content which is otherwise legal (even if some reactionary or conservative groups consider it controversial). It is much better to say upfront that something is going to allow all "legal" uses.

I'm considering closing this issue, if there are strong feelings against the implementation of an 'ethical use' document.

**Comment by afarlie** [comment]
Closed per comments made  in https://github.com/Stability-AI/StableLM/issues/3
