### ISSUE TITLE
The program does not start

### ISSUE THREAD

**Issue by Savel314** [nomic-ai/gpt4all-chat#251]
After installing any version of gpt, the program closes and no longer opens. Restarting the computer, disabling antivirus and all programs does not help.

**Comment by jans1981** [comment]
you need to have avx2 and fma3 instrucions on your cpu , you can see it downloading cpu-z program and see your pcu instructions specifications

**Comment by Savel314** [comment]
I don't have these instructions on the processor. What to do?

**Comment by manyoso** [comment]
download and install the avx-only version
