### ISSUE TITLE
trying to run chat on Ubuntu 20.04.6 LTS getting loads of GLIBC not found errors

### ISSUE THREAD

**Issue by G4GUO** [nomic-ai/gpt4all-chat#26]
This problem was mentioned under a different heading

When I try to run ./chat I get 
./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat)
./chat: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat)
./chat: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/charles/gpt4all0.1.0/bin/../lib/libicuuc.so.70)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/charles/gpt4all0.1.0/bin/../lib/libicuuc.so.70)

**Comment by thiagodma** [comment]
I'm getting similar behaviour:

```
./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70)
```

**Comment by fastrizwaan** [comment]
could u try this 
https://github.com/fastrizwaan/gpt4all-libs/releases/tag/0.1.0

**Comment by G4GUO** [comment]
That clears the GLIBCXX linker errors but not the libc related ones
my libc points to libc-2.31.so

./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)

**Comment by fastrizwaan** [comment]
I'm not sure whether libc will work, but you can try `https://packages.ubuntu.com/jammy/libc6` extracting https://packages.ubuntu.com/jammy/amd64/libc6/download (right click on the mirror link and save as) and open the deb file with file-roller (archive manager) and extract `data.tar.zst` to lib may work.

![image](https://user-images.githubusercontent.com/1161682/232135526-a48c5872-9bbf-453d-b9bf-f26904b334a7.png)

**Comment by G4GUO** [comment]
Sadly I just get a core dump. Thanks for your efforts anyhow.

I also tried to build the program from the git repository but I am having issues with Qt6 libraries.

**Comment by fastrizwaan** [comment]
no worries, https://open-assistant.io/ is much better than this not so good gpt4all

**Comment by G4GUO** [comment]
![Screenshot from 2023-04-14 21-39-33](https://user-images.githubusercontent.com/4476944/232150553-a4020985-ca27-42f0-a464-d7d07f58caf0.png)

I finally managed to build it, then use the model that came with the install but it seems a bit wonky

**Comment by thiagodma** [comment]
@G4GUO can you share how you managed to build it?

**Comment by G4GUO** [comment]
I followed the instructions here
https://github.com/nomic-ai/gpt4all-chat
I installed Qt6 to a local directory on my machine and then in the CMakeLists.txt in the  gpt4all-chat I added a line to point to where I had installed Qt6 (see below)
SET(Qt6_DIR "/home/charles/Qt/6.5.0/gcc_64/lib/cmake/Qt6")
I then used the model file that comes with the nomic ai installation program https://gpt4all.io/installers/gpt4all-0.1.0-Linux.run
That was it. Hopefully I have all the right bits !! I think I may have mixed the old GPT-J an new Chat4all code though.

**Comment by thiagodma** [comment]
Ok! I'll give it a try! Thanks

**Comment by G4GUO** [comment]
Good luck!

**Comment by mofosyne** [comment]
Confirmed working.

Just remember when cloning the repo to also run `git submodule update --init --recursive`, instructions forgot to mention that.

As for locating your local gcc cmake Qt6 instance just run 

```
locate Qt6 | grep gcc_64/lib/cmake/Qt6 | head -1
```

This should get you your `SET(Qt6_DIR "<Path to local gcc cmake Qt6 instance>")` to place on top of your CMakeLists.txt just under `cmake_minimum_required(VERSION 3.16)`.

Now you can run the rest of the build step then... copy over the model and quantize it before running the chat UI

```
cd gpt4all-chat
mkdir build
cd build
cmake ..
cmake --build . --parallel
cp /opt/gpt4all/bin/ggml-gpt4all-j-v1.2-jazzy.bin ggml-gpt4all-j-v1.2-jazzy.bin
./bin/gpt-j-quantize ggml-gpt4all-j-v1.2-jazzy.bin ./ggml-model-q4_0.bin 2
./chat
```

Here is the result, looks like I broke the bot's brain somehow lol.

![image](https://user-images.githubusercontent.com/827793/233239382-65c59b6f-3408-4583-aeca-ffec28231103.png)

**Comment by manyoso** [comment]
Ubuntu 22.04 is required.
