### ISSUE TITLE
License was changed to MIT after being GPL and being worked on by multiple people; This violates the GPL.

### ISSUE THREAD

**Issue by duaneking** [nomic-ai/gpt4all-chat#273]
Respectfully while I love the idea, you poisoned the well by being sloppy with the legal stuff.

Why was this done?

https://github.com/nomic-ai/gpt4all-chat/commit/ef711b305b6b85f6366f15ccce2c10d10df74902

You can't just casually change your projects license like that, once people have put commits into it that only works if only a single person is the only person who have worked on it. Thats not the case here, as the git log shows. Multiple people worked on a GPL project and did not sign off to have the project relicensed to MIT.

So this project is currently a MIT fork of a GPL project that does not respect the GPL, and that violates the GPL and it violates the rights of everybody who worked on it while it was marked as GPL and not MIT, who did not consent to have their code license changed.

Based only on the log I saw by accident while trying to figure out how to Install this without dropping a statically compiled binary of unknown origin on to my machine, This choice was arbitrarily made by only one individual after multiple people checked in and committed code and then others helped it along when it was found that it had been poorly done; not only is this violating the rights of the people who worked on it when it was GPL before, but they're now trying to say that it's MIT when it's not, its still GPL.

You cant just de-GPL GPL code. That's not how that works.

**Comment by AGENT-LLM** [comment]
Are you the FOSS police or something? 
How do you know they didn't reach out to <5 contributors before the license switched?

**Comment by duaneking** [comment]
There is no evidence of that happening based on the record; Generally, for such a PR, all the people previously would have signed off, and not didn't happen. So there is. So there is no record of that happening.

The fact of the matter is, I was scoping out the project because I'm a professional developer, and I was interested in helping it a bit this weekend. But I can't do that if the legal providence of the project is in question.

Part of being a good engineer is respecting the licensing of the code that you encounter. So As much as you might want to make rude comments, the fact is anybody who steals open source code is stealing from all of us.

**Comment by manyoso** [comment]
@duaneking please show the commit of the person whose rights you think have been violated. This code was written by me and I'm well within my right to relicense how I see fit.

**Comment by duaneking** [comment]
I linked to the commit that changed the license above; every commit that was made before that was made as a GPL contribution.  Here it is again: https://github.com/nomic-ai/gpt4all-chat/commit/ef711b305b6b85f6366f15ccce2c10d10df74902

Looking at the commit log that is all public, there are multiple people who did not sign off.  This is important because it's not just about them making waves; You seem to think that it's OK and you have the authority to change the license as long as they don't disagree enough to file a complaint. But that's not how this works. I actually learned about this the hard way myself, because I worked on a project that ended up using a license that ended up killing it, because the license ended up being the issue. And so it wasn't worth working on anymore. And I don't want that to happen to others. Imagine how sad you would be if you gave this project all your time and then some lawyer at MegaCorp used that to shut it down. By my bringing this up now, it gives you the ability to take care of things before this becomes bigger.

In an attempt to show good faith here is the people I found according to the git log:

https://github.com/nomic-ai/gpt4all-chat/commits?author=adtreat
https://github.com/nomic-ai/gpt4all-chat/commits?author=AndriyMulyar
https://github.com/nomic-ai/gpt4all-chat/commits?author=apage43
https://github.com/nomic-ai/gpt4all-chat/commits?author=zanussbaum
https://github.com/nomic-ai/gpt4all-chat/commits?author=manyoso
https://github.com/nomic-ai/gpt4all-chat/commits?author=TheBloke

The reason this matters to me is because I was actually looking to throw some code at this today/this weekend, and this situation means I can't, because I don't want to work on another project that I'm going to have to watch die due to its licensing issues.

**Comment by jans1981** [comment]
i thinks these people sold by money the project to some big corporation

**Comment by manyoso** [comment]
I understand you are acting and commenting in good faith, but everyone one of those contributors has signed off on the license change. I have personal knowledge of this. 

There is no problem. 

> The reason this matters to me is because I was actually looking to throw some code at this today/this weekend, and this situation means I can't, because I don't want to work on another project that I'm going to have to watch die due to its licensing issues.

**Comment by duaneking** [comment]
As you are admitting that not everybody has signed off, my original point stands.
