### ISSUE TITLE
Linux: error while loading shared libraries: libxcb-cursor.so.0 (SOLVED)

### ISSUE THREAD

**Issue by lojik-ng** [nomic-ai/gpt4all-chat#3]
I had the above error while trying to run it on linux mint and i fixed it by installing the missing libray with the command below:

sudo apt install libxcb-cursor0

I hope this helps someone.

**Comment by manyoso** [comment]
Yep, it was made on ubuntu but not totally surprised there is some missing deps

**Comment by luckycold** [comment]
Same issue but with libjpeg on Fedora.

**Comment by CBevers** [comment]
After I installed libxcb-cursor0 I started getting these errors when running chat:
./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70)

Can anyone give me some tips? I'm running a WSL 2 version of Ubuntu 20.04.5 LTS.

**Comment by moh21amed** [comment]
> After I installed libxcb-cursor0 I started getting these errors when running chat: ./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70)
> 
> Can anyone give me some tips? I'm running a WSL 2 version of Ubuntu 20.04.5 LTS.

same on zorin os

**Comment by insigmo** [comment]
> After I installed libxcb-cursor0 I started getting these errors when running chat: ./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70) ./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all 0.1.0/bin/../lib/libicuuc.so.70)
> 
> Can anyone give me some tips? I'm running a WSL 2 version of Ubuntu 20.04.5 LTS.

same on real ubuntu 20.04

**Comment by alaneku** [comment]
After I installed libxcb-cursor0, the  the chat window started to open but crashed giving the following error

QML debugging is enabled. Only use this in a safe environment.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
gptj_model_load: loading model from 'ggml-gpt4all-j.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401,45 MB
gptj_model_load: memory_size =  1792,00 MB, n_mem = 57344
gptj_model_load: ................................Killed

I am running Mint 21,1

**Comment by MisterE123** [comment]
BTW, this probably should not be marked solved, as these dependencies should probably be included in the installer. The long term solution is probably setting up a package manager package.

**Comment by MoshiMaster** [comment]
I'm on Ubuntu 22.04 WSL via Windows 11, I tried the command above but still get the same error:
`error while loading shared libraries: libxcb-glx.so.0: cannot open shared object file: No such file or directory`

**Comment by MisterE123** [comment]
> I'm on Ubuntu 22.04 WSL via Windows 11, I tried the command `sudo apt install libxcb-cursor0` but still get the same error: `error while loading shared libraries: libxcb-glx.so.0: cannot open shared object file: No such file or directory`

I installed all of these:https://github.com/nomic-ai/gpt4all-chat/issues/3#issuecomment-1508302969

**Comment by hacker-szabo** [comment]
> I installed all of these:[#3 (comment)](https://github.com/nomic-ai/gpt4all-chat/issues/3#issuecomment-1508302969)

what is your mint's version? It still did not work for me

**Comment by EinGeist** [comment]
I'm using linux ubuntu 22.04
I have the same error 
solved it with installing the dependency using the command:
sudo apt install libxcb-cursor0

**Comment by Gabriel-Alves-Cunha** [comment]
Doesn't work for Fedora :cry: :cry: :cry: :cry: :cry: :cry: 

P.S.: For `./chat: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory`
I managed to solve by doing:
```sh
sudo dnf copr enable aflyhorse/libjpeg
sudo dnf install libjpeg.so.8
```

Does anyone know of some repo to download this `libxcb-cursor0`??

**Comment by sgoettel** [comment]
> sudo apt-get install build-essentials (already installed on mint) sudo apt-get install libicu-dev sudo apt-get install libxcb-cursor-dev
> 
> confirmed working on mint

I second this.

**Comment by badou01** [comment]
> Same issue but with libjpeg on Fedora but doesn't solve the issue if you install the package using dnf since it's already installed.

Bro I had the same issue today without Fedora 37. I fixed it by download first this file: https://rpmfind.net/linux/openmandriva/cooker/repository/x86_64/main/release/lib64jpeg8-2.1.5.1-1-omv2390.x86_64.rpm  and secondly file  : https://rpmfind.net/linux/opensuse/tumbleweed/repo/oss/x86_64/libxcb-cursor0-0.1.4-1.2.x86_64.rpm 
then you install each of them by doing 
sudo rpm -i lib64jpeg8-2.1.5.1-1-omv2390.x86_64.rpm
and----
sudo rpm -i libxcb-cursor0-0.1.4-1.2.x86_64.rpm

**Comment by fastjack77** [comment]
```
user@computer:/opt/gpt4all/bin$ ./chat
./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all/bin/../lib/libicuuc.so.70)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all/bin/../lib/libicuuc.so.70)
```
On Linux Mint 20.3, amd64

**Comment by GodsBadAssBlade** [comment]
BIG THANKS FROM POP OS

**Comment by AugustasV** [comment]
This should be pinned in README file!
