### ISSUE TITLE
Win 32 build for older windows ...

### ISSUE THREAD

**Issue by afarlie** [nomic-ai/gpt4all-chat#30]
Hi. 

Is it possible to have a version for Win32 on Windows 7 ? 

I'm fine with a console version as long as I can log the outputs somehow.. 

Thanks.

**Comment by todstelzer** [comment]
Windows 7 no longer gets security updates. So I don't think there will be a Windows 7 version.

**Comment by afarlie** [comment]
Fair.    The installer I found was Win64 only though.  Alternatively are there plans to create an online service version?  (subject to any ethical usage policy terms a potential provider might impose, even if the model itself isn't limited.)

**Comment by manyoso** [comment]
No, we can't support this old.
