### ISSUE TITLE
Missing libxcb-xinerama.so.0? (SOLVED)

### ISSUE THREAD

**Issue by DrDogGPT** [nomic-ai/gpt4all-chat#31]
Full message -- "./gpt4all-0.1.0-Linux.run: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory"

Happens during installer phase. Running Ubuntu 20.04.

**Comment by hrohrweck** [comment]
Had the same issue, `sudo apt install libxcb-xinerama0 libxcb-cursor0` fixed it

**Comment by DrDogGPT** [comment]
Ok. Thanks.

**Comment by manyoso** [comment]
Fixed.
