### ISSUE TITLE
Feature request: "Prompt" repository.

### ISSUE THREAD

**Issue by afarlie** [nomic-ai/gpt4all-chat#34]
Less of an idea to do with the tool or model, but a feature suggestion.

Would it be possible for there to be some kind of 'prompt' wiki or repository, whereby users (willing and able) to share prompts under creative commons CC-BY or CC-BY-SA terms , would be able to submit prompts for use by other individuals (subject to any ethical use policy that gets implemented.) ?     The need for attribution on these is that lengthy prompts have of themselves a potentially creative element, and in line with 'free' (GNU sense) ideals, I'd like to share prompt ideas others may be able to build on.

**Comment by manyoso** [comment]
It is coming and likely this next week.
