### ISSUE TITLE
M1 os 13.3.1  "Cannot open “gpt4all-0.1.0-Darwin.app” because the developer cannot be verified." (SOLVED)

### ISSUE THREAD

**Issue by zhongtianxin** [nomic-ai/gpt4all-chat#35]
"Cannot open “gpt4all-0.1.0-Darwin.app” because the developer cannot be verified."

Apple M1 内存 8 GB.   macos 13.3.1 (22E261)

**Comment by zhongtianxin** [comment]
Find the application that cannot be opened, right-click to open it, and the first time a prompt box will appear, select the “Open Anyway” button.

**Comment by sebasmos** [comment]
> 
or do [this](https://github.com/nomic-ai/gpt4all-chat/issues/57#issuecomment-1510689517)

**Comment by AndriyMulyar** [comment]
Will be fixed when we get certificates signed. Waiting on Apple.

**Comment by manyoso** [comment]
We're signed now.
