### ISSUE TITLE
`GLIBC_2.35' not found (required by ./chat)

### ISSUE THREAD

**Issue by moh21amed** [nomic-ai/gpt4all-chat#38]
I am running zorin os 16 when i run chat excutable it gives me this error :
./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/mohamed/AI/gpt4all/bin/../lib/libicuuc.so.70)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/mohamed/AI/gpt4all/bin/../lib/libicuuc.so.70)

**Comment by AdamK222** [comment]
same on Ubuntu

**Comment by manyoso** [comment]
Which version of Ubuntu? this was made on Ubuntu 22.04

**Comment by mtthw-meyer** [comment]
Same issue on Mint 20.3.

```
./chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./chat)
./chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chat)
```

**Comment by moh21amed** [comment]
Do anyone found the solution?

**Comment by mtthw-meyer** [comment]
I upgraded my mint to 21 which is based on Ubuntu 22. Sounds like Zorin 17 will be based on Ubuntu 22 as well. Probably have to build it from source yourself for Zorin 16.

**Comment by EchedeyLR** [comment]
This should be built agains't the oldest supported LTS to ensure compatibility.

```
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all/bin/chat)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all/bin/../lib/libicuuc.so.70)
/opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all/bin/../lib/libicuuc.so.70)
```

I guess this while running on Debian 11 (equivalent to Ubuntu 20.04). Is that or make the installer based on AppImage or Flatpak.

**Comment by moh21amed** [comment]
> This should be built agains't the oldest supported LTS to ensure compatibility.
> 
> ```
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all/bin/chat)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/gpt4all/bin/../lib/libicuuc.so.70)
> /opt/gpt4all/bin/chat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/gpt4all/bin/../lib/libicuuc.so.70)
> ```
> 
> I guess this while running on Debian 11 (equivalent to Ubuntu 20.04). Is that or make the installer based on AppImage or Flatpak.

Please could you built it and upload it here as i have limited internet connection right now and i can't download the whole qt framework , please ?

**Comment by manyoso** [comment]
Ubuntu 22.04 is rquired.
