### ISSUE TITLE
UI doesnt load on Ubuntu 22.04 (chat program not working) no response, drops back to prompt immediately

### ISSUE THREAD

**Issue by mhadjih2** [nomic-ai/gpt4all-chat#45]
I've installed GPT4ALL-J via the instructions provided on the GitHub. Left everything in the installer as is, otherwise you get permission errors while copying file to .desktop. When I go to the directory under /opt/gpt4all/bin and try to start the chat-program, nothing happens. It drops immediately back to the prompt, no error-message, no window.

Ubuntu 22.04 (fully updated)
Asus Z390-H 
Intel I5 - 9600K
32 GB memory
Asus R390X (8GB)

**Comment by slawekmikula** [comment]
I have installed it right now. Also on 22.04. One library was missing: libxcb-cursor. When I installed this all went OK. Maybe this will help you.  If this won't help maybe try `ldd chat` in the console and look what libraries are missing.

**Comment by slawekmikula** [comment]
Maybe connected with #31

**Comment by mhadjih2** [comment]
@slawekmikula :100: 
That was the solution indeed!

sudo apt install libxcb-xinerama0 libxcb-cursor0
