### ISSUE TITLE
Installation on Linux Mint 21.0 (Vanessa) (SOLVED)

### ISSUE THREAD

**Issue by daniel-lewis-ab** [nomic-ai/gpt4all-chat#46]
This is from memory, but it'll provide a starting point:

```BASH
sudo chmod +x ./gpt4all-installer.run
sudo apt install libxcb0
sudo ./gpt4all-installer.run
```

That will likely get you installed, following the instructions.  I personally don't put it in /opt/ but suit yourself.
After that, cd into the appropriate directory.  To run the updater:

```BASH
sudo ./maintenancetool
```

To run the GPT-J chat program:

```BASH
./bin/chat
```

**Comment by daniel-lewis-ab** [comment]
Oh - and be mindful not to just write
```BASH
chat
```
Because that will run a totally different program within Linux

**Comment by IntrovertedFL** [comment]
I'm getting this error when I try to run on Linux Mint 21.0. Do you have any suggestions @daniel-lewis-ab? 

```/opt/gpt4all 0.1.0$ sudo ./maintenancetool
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, xcb.```
