### ISSUE TITLE
Win 8 chat.exe - entry point not found (Qt6Gui.dll)

### ISSUE THREAD

**Issue by zrodrps** [nomic-ai/gpt4all-chat#48]
Installed win win64 installer, on an older laptop win 8. Tried to run it and got this msg popup

![image](https://user-images.githubusercontent.com/37600191/232264463-207981a1-e6e9-4b5e-b3e9-a6c91ad2f297.png)

**Comment by bogwero** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/82623015/232305560-0a089a2e-16a5-4c14-a90f-3f05190e1b66.png">

**Comment by alexdroidcuba** [comment]
same problem in win 8.1 :(

**Comment by manyoso** [comment]
Most likely you have too old of Windows. The dll in question was built for new windows. We have no plans to support older like this, but you can always compile from source. Sorry.
