### ISSUE TITLE
Not accepting correction, is it?  (No HF? )

### ISSUE THREAD

**Issue by drscotthawley** [nomic-ai/gpt4all-chat#5]
I'm finding it keeps repeating the same incorrect answer, and even tells me I'm wrong! lol

<img width="943" alt="Screen Shot 2023-04-13 at 6 58 14 PM" src="https://user-images.githubusercontent.com/13925685/231907897-9781191a-03c0-43ca-a298-8c4b3bc6a613.png">

Mac Build. Mac OS 12.6.5. Installer worked great after I updated from 12.3.

**Comment by xudru** [comment]
Yes, i have the same experience. I asked it about a german battleship and it told me it was sunk in 1944 (what is correct) but it told me also that Admiral Doenitz was on board and killed (In reality he died in 1980). I told it this fact and it said im incorrect. Then i asked it about Doenitz and it said he commissioned the first german nuclear submarine in 1944!
