### ISSUE TITLE
"...because it is not supported on this type of Mac"

### ISSUE THREAD

**Issue by justaverysimplequestion** [nomic-ai/gpt4all-chat#50]
MacBookPro 16' 2019, MacOs Ventura 13

**Comment by Critical11** [comment]
Need support for darwin-x64-ver

**Comment by AndreasFxPro** [comment]
Same on MacBook Pro 15' 2018, MacOS Ventura (i7-8850H)

**Comment by AndriyMulyar** [comment]
Noted. Compiled versions for Intel based Macs coming soon.
To get it faster, you can search the discord history where hackers have already pre-built these binaries and give instructions on how you can do it yourself.
