### ISSUE TITLE
ubuntu20.04 Seems to have no idea what to do with .'run' filetype with execute permissions.. Help?

### ISSUE THREAD

**Issue by Waltsfo** [nomic-ai/gpt4all-chat#54]

**Comment by AndriyMulyar** [comment]
On Ubuntu, you must first make the file executable. You can run `chmod o+rwx filename.run` to do this. Then, run the installer with `./filename.run`!

**Comment by laura-i-c** [comment]
Under Ubuntu, to make this file executable, open the properties of the file, permissions and check execution: allow the execution of the file as a program. That's what worked for me.

![Capture d’écran du 2023-04-17 11-30-15](https://user-images.githubusercontent.com/130976799/232444472-6ce1b269-5344-4b11-9f22-3c3aed0ebae2.png)
