### ISSUE TITLE
gptj.cpp license

### ISSUE THREAD

**Issue by loretoparisi** [nomic-ai/gpt4all-chat#56]
Is it possibile to split the GUID (Qt dependant files) and the GGML/llama dependant sources in different projects? That would make possibile to ship the `gptj.cpp, gptj.h` sources without the GPL license, in order to let GPT4All-J to be supported into llama /ggml (parent) project itself.

https://github.com/ggerganov/llama.cpp/issues/984#issuecomment-1510199081

**Comment by manyoso** [comment]
I've just updated the license to MIT. Point is moot.
