### ISSUE TITLE
iMac m1 will not allow file to open (WORKAROUND)

### ISSUE THREAD

**Issue by joey5518** [nomic-ai/gpt4all-chat#57]
“gpt4all-0.1.0-Darwin.app” cannot be opened because the developer cannot be verified.

**Comment by jfink99** [comment]
System Settings --> Privacy and Security --> Scroll down and allow gpt4all

**Comment by manyoso** [comment]
In very near future it will be codesigned.

**Comment by codazoda** [comment]
You can also try to right-click on the executable and select open, which will give you the error but still allow you to open it.

**Comment by sebasmos** [comment]
> 

This works, same issue [here](https://github.com/nomic-ai/gpt4all-chat/issues/35 )

**Comment by manyoso** [comment]
We're code signed now.
