### ISSUE TITLE
How to improve gpt4all-chat or how to expand its knowledge?

### ISSUE THREAD

**Issue by ccartermices** [nomic-ai/gpt4all-chat#58]
I have installed gpt4all on my win10 computor. However, it reapeated "I don't know" when I asked it some questions (but the questions in github's example can work). How to improve gpt4all-chat or how to expand its knowledge?

**Comment by behhzadd** [comment]
I have win 10 on my laptop but the chat.exe doesn't work.any idea to help me?

**Comment by manyoso** [comment]
there will be an update soon that will greatly expand. check back in a few hours

**Comment by ch01ca** [comment]
I installed windows UI and it do mot answer questions too. What's the cause?

**Comment by manyoso** [comment]
Check back for updates as things are improving quickly. Closing for now as it is to generic a task to execute on.
