### ISSUE TITLE
Ability to use other LLM models (Dolly v2, Cerebras-13b, etc)?

### ISSUE THREAD

**Issue by elementalcollision** [nomic-ai/gpt4all-chat#6]
Currently have the GPT-J model from Databricks (Dolly v2-12b) available and was wondering if I could map this to the overall GPT4All application?  

This is specifically to be run on an M1 Max MBP w/OSX 13.1.x

LLM in reference is here: [databricks/dolly-v2-12b](https://huggingface.co/databricks/dolly-v2-12b/blob/main/pytorch_model.bin)

**Comment by manyoso** [comment]
On the feature wish list and coming!

**Comment by elementalcollision** [comment]
Excellent.  Noticed the hooks were being put in place based on commits so,
looking forward to being able to test alternative models out.

**Comment by elementalcollision** [comment]
Since this is pending for wish list, I'll go ahead and close.
