### ISSUE TITLE
not be able to execute "chat" (PROBABLY MISSING AVX2)

### ISSUE THREAD

**Issue by long3888** [nomic-ai/gpt4all-chat#65]
I did click the chat in bin folder or run as admin but it does not work after installation

**Comment by pyTony** [comment]
I clicked the chat.exe and after opened the terminal. chat.exe only exits immediately without doing anything.
![image](https://user-images.githubusercontent.com/2307944/232753580-16d2f050-39d4-4eb8-8cd3-2b70d8287011.png)

**Comment by manyoso** [comment]
Can you confirm that you have AVX2 support on your hardware?

**Comment by HappyPony** [comment]
I have 
> intel-Core-i3-2310M 2.1 GHz
> Sandy Bridge microarchitecture (2nd generation)

https://en.wikipedia.org/wiki/List_of_Intel_Core_i3_processors

Chat.exe shows the same behavior as described above. CPU supports AVX, I know that. How can I find out if it supports AVX2?

**Comment by long3888** [comment]
> Can you confirm that you have AVX2 support on your hardware?

thank you, I check it on Steam and I see that I do not have  AVX2 support on my hardware. But what part can I buy to have it support?

**Comment by pyTony** [comment]
Intel(R) Core(TM) i7-3770 CPU and GTX750Ti

**Comment by HappyPony** [comment]
Is it expected that GPT4All will be further developed so that GPT4All will also work with CPU without AVX2?
