### ISSUE TITLE
How to allocate resources to chat app/ai?

### ISSUE THREAD

**Issue by joseffb-mla** [nomic-ai/gpt4all-chat#67]
How do I tell the application to use X gb of mem and X CPU's? 

it's pretty slow on replying back to a simple hello.

Thank you very much, this is a very good idea as a project!

**Comment by apage43** [comment]
prompt batch size lets you allocate more ram to prompt processing but that will only affect the amount of time it takes to *start* displaying text, CPU thread count (modifiable after linked PR lands) will be the main driver of generation speed
