### ISSUE TITLE
Installer Incorrectly Checks System Disk Space Instead of Target Installation Disk on Windows

### ISSUE THREAD

**Issue by MillionthOdin16** [nomic-ai/gpt4all-chat#69]
Installer doesn't check disk space of the target installation disk on Windows. It uses the default system disk.

For example, if my system disk (C) has 3GB of space, but during install I designate the installer to use disk D as the target, the install will fail and tell me I only have 3GB of space available for the install.

**Comment by manyoso** [comment]
Likely a problem with Qt installer framework. You should lodge this bug against upstream qt installer framework as this project cannot fix it.
