### ISSUE TITLE
Can installer skip downloading?

### ISSUE THREAD

**Issue by rexzhang360** [nomic-ai/gpt4all-chat#7]
Is there any way can add a feature let the user choose to download or not during the installation process?

**Comment by manyoso** [comment]
If you don't download no install will take place. What do you have in mind here?

**Comment by rexzhang360** [comment]
What I mean is, while installing the essential components, exclude the bin file, which is taking a long time to download. Is that can be done?

**Comment by manyoso** [comment]
No, it is installing only essential components
