### ISSUE TITLE
When will Chinese be supported, is there a plan?

### ISSUE THREAD

**Issue by ahkimkoo** [nomic-ai/gpt4all-chat#70]
When will Chinese be supported, is there a plan?
什么时候会支持中文，有计划么？

**Comment by manyoso** [comment]
Like with many other languages soon^TM

**Comment by ccy2222** [comment]
Hahaha, support for Chinese earlier! Keep it up.

**Comment by manyoso** [comment]
There is a plan and multilanguage support is coming.

**Comment by ccy2222** [comment]
😍

AT ***@***.***> 于2023年5月10日周三 00:54写道：
