### ISSUE TITLE
Compilation failed: undefined reference to typeinfo for LLModel

### ISSUE THREAD

**Issue by beckapm** [nomic-ai/gpt4all-chat#72]
Had an error while compiling, solved it by adding =0 to virtual functions in llmodel.h (line 22 and 23)

```
virtual void setThreadCount(int32_t n_threads) **= 0**;
virtual int32_t threadCount() **= 0**;
```

**Comment by blasferna** [comment]
I have the same issue.

**Comment by Rhialto** [comment]
Here as well.... I tried two different versions of gcc (7 and 10) but both behaved the same.

**Comment by manyoso** [comment]
fixed. just rebase and try again.
