### ISSUE TITLE
Massive lag spikes with Freesync on

### ISSUE THREAD

**Issue by alomex21** [nomic-ai/gpt4all-chat#73]
Windows 10 21H2
I5-9600K
RTX3070

Monitor: XG270QC 165Hz Freesync Premium Pro

While using the chat, the monitor flickers constantly and seeing the OSD from the monitor, it goes below 50 Hz for a few miliseconds.

You can reproduce this issue by using the chat on the display with this technology. I'm not sure about G-Sync monitors can reproduce this issue aswell.

**Comment by manyoso** [comment]
This is old style cathode ray tube style monitor??

**Comment by manyoso** [comment]
Not specific to this software but likely all modern software using GUI for drawing.
