### ISSUE TITLE
Error From cmake During Installation

### ISSUE THREAD

**Issue by websmyths** [nomic-ai/gpt4all-chat#8]
I'm attempting to install it on a 2019 Intel MacBook Pro. I tried to download the Mac Installer file, but it would start and quit. Tried several times and only got a partial download. So I tried the manual install. I downloaded and installed Qt and Cmake. I got as far as executing "cmake .." from the build folder, and I get the following error: 

`CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" (requested
  version 6.2) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
`
Also, where do I put the model file(s) once I successfully install it?

**Comment by 2187Nick** [comment]
In the CMakeLists.txt file. I added  list(APPEND CMAKE_PREFIX_PATH "C:/Qt/6.5.0/mingw_64/lib/cmake/Qt6")

Adjust the location according to where you installed Qt.

**Comment by iplayfast** [comment]
What a terrible experience. can we have a simple g++ without all the QT extras. I've been trying to install this for hours now.

**Comment by Fax** [comment]
I haven't used qt in ages, so I am not aware of their licensing system works. 
It's asking me to register an account to retrieve the libraries required to build the project. 
Unless I am doing something really wrong, why was QT chosen for this project?

**Comment by websmyths** [comment]
I brew installed qt and sourced my zshrc and zprofile. Don't know if the other two steps were necessary, but now it's working. Thanks for the suggestions above.

`brew install qt
source ~/.zshrc
source ~/.zprofile`
