### ISSUE TITLE
The windows installer can't download!

### ISSUE THREAD

**Issue by Burgeon0110** [nomic-ai/gpt4all-chat#80]
![image](https://user-images.githubusercontent.com/128889876/233495821-a467dbbc-1a3f-4a1c-bd20-018edce564cd.png)

**Comment by manyoso** [comment]
Has anyone else seen this?

**Comment by manyoso** [comment]
Closing as no one else seems to have seen this and it is almost undoubtedly a client side issue.

**Comment by Burgeon0110** [comment]
Do you try it?
