### ISSUE TITLE
All UI colors should be hardcoded

### ISSUE THREAD

**Issue by apage43** [nomic-ai/gpt4all-chat#85]
Colors are currently inconsistent across different machines (or OS configuration?)

ideally put these all in one place in the qml instead of spread out everywhere

![image](https://user-images.githubusercontent.com/169252/233662482-d5638931-d4af-45db-bad0-4e235360bebd.png)
![image](https://user-images.githubusercontent.com/169252/233662566-fe9fde2f-5c9b-48d5-ae6a-54cdf93e8147.png)

**Comment by RassilonSleeps** [comment]
![Screenshot_2023-04-21_08-31-42](https://user-images.githubusercontent.com/64247429/233662963-98e158fb-c1e6-4b2d-99dc-c20adf13b383.png)
Potentially related, highlighted selection text in model drop-down is unreadable.

**Comment by manyoso** [comment]
Which OS are you on?

**Comment by manyoso** [comment]
Fixed
