### ISSUE TITLE
QML Settings error. Settings is not a type.

### ISSUE THREAD

**Issue by kuvaus** [nomic-ai/gpt4all-chat#90]
Building from source on Intel Mac with Mac OS Monterey.

I installed Qt version 6.4.3 and Qt-Creator using Homebrew. The chat.app builds but when I try to run it, I get the following error:

```sh
QQmlApplicationEngine failed to load component
qrc:/gpt4all-chat/main.qml:118:9: Settings is not a type
```

This can be fixed by adding Qt.labs.settings into the main.qml file.
Then, after rebuild the chat.app will launch just fine.
I'll create a pull request for a patch.

**Comment by manyoso** [comment]
You should rebase and get the latest changes and this should go away. The fix was to add Core in the CMakeLists.txt to the required modules.
