### ISSUE TITLE
[Binding/UI] Node-RED node and flow for GPT4All-J

### ISSUE THREAD

**Issue by rozek** [nomic-ai/gpt4all-chat#93]
Hi!

First of all: thank you very much for your marvellous contribution! Being able to run inferences on one's CPU is awesome!

Using gpt4all-chat as its workhorse, I have built function nodes and complete flows for Node-RED, which can be used to run inferences based on the [GPT4All-J](https://github.com/rozek/node-red-flow-gpt4all-j) model.

[Node-RED](https://nodered.org/) is a data flow processor which allows people ranging from none over casual up to professional programmers to build complex systems from within their browsers just by wiring components (aka "nodes") together.

Having the GPT4All-J model as such nodes allows these people to create their own user interfaces or even build their own autonomous agents, always having full control over everything they do!

Thanks again for your contribution!

With greetings from Germany,

Andreas Rozek

**Comment by manyoso** [comment]
Cool! Thanks for sharing :)
