### ISSUE TITLE
Installer fails when trying to copy to /root/Desktop

### ISSUE THREAD

**Issue by bradshimmin** [nomic-ai/gpt4all-chat#94]
Hello folks. Running the .run installer on Pop!_OS just now, I've run into an error toward the end with a pop-up that says "Can't copy "/usr/share/applications/GPT4AllChat.desktop" to "/root/Desktop/GPT4AllChat.desktop": Cannot create /root/Desktop/GPT4AllChat.desktop for output

I've tried re-running the script in Sudo mode, but that fails as well. I fear this is one of those small distribution complexities. Still, has anyone else run into this and found a way through?

Thanks!
b.

**Comment by manyoso** [comment]
Sorry about this, but not sure what the problem is. However, I can tell you that in most recent source code we're no longer trying to make a desktop file in /usr/share/applications so this problem will go away with next installer release.
