### ISSUE TITLE
CLI: Incomplete response

### ISSUE THREAD

**Issue by aaambrosio** [nomic-ai/gpt4all-chat#95]
I'm running the CLI tools. Responses are incomplete:

`./bin/gpt-j -m ggml-gpt4all-j-v1.2-jazzy.bin -n 200 --top_k 40 --top_p 0.9 -b 9 --temp 0.9 -p "Create an essay about a pet dog named Nubi."`
![Screenshot 2023-04-23 at 6 11 55 AM](https://user-images.githubusercontent.com/41741367/233809004-7ba21cbd-7714-4687-bde8-8f3a83e4a70b.png)

Am I missing something?

**Comment by manyoso** [comment]
The CLI is not supported in this repo.
