### ISSUE TITLE
GPT4ALL for win10 can be successfully installed, run chat.exe without any prompts.

### ISSUE THREAD

**Issue by Burgeon0110** [nomic-ai/gpt4all-chat#96]
Chat.exe doesn't work.

错误应用程序名称: chat.exe，版本: 0.0.0.0，时间戳: 0x643da578
错误模块名称: chat.exe，版本: 0.0.0.0，时间戳: 0x643da578
异常代码: 0xc000001d
错误偏移量: 0x0000000000020517
错误进程 ID: 0x1c54
错误应用程序启动时间: 0x01d9763870e762b3
错误应用程序路径: E:\gpt4all\bin\chat.exe
错误模块路径: E:\gpt4all\bin\chat.exe
报告 ID: 393506d1-1344-4355-90b1-27901e6be4d6
错误程序包全名: 
错误程序包相对应用程序 ID:

由于下列某个原因，Windows 无法访问文件 : 网络连接、存储文件的磁盘或安装在此计算机上的存储 驱动程序有问题；或者磁盘丢失。 由于上述错误，Windows 关闭了程序 chat.exe。

程序: chat.exe
文件:

**Comment by manyoso** [comment]
Please try again. I just updated with a new release.

**Comment by Burgeon0110** [comment]
Why are there previous download issues again?

![image](https://user-images.githubusercontent.com/128889876/234143609-c51e9c14-acb3-483b-9998-a8b605cfd5ca.png)

**Comment by Burgeon0110** [comment]
I can't download the bin file.
![image](https://user-images.githubusercontent.com/128889876/234203122-9c7d28f8-980b-4c07-a5ba-197b0514c0f0.png)

**Comment by Burgeon0110** [comment]
Why can't I download the bin file?

![image](https://user-images.githubusercontent.com/128889876/234298640-ab6d6650-0bc0-4d8d-b5c0-334cbb3381de.png)

**Comment by Burgeon0110** [comment]
DEAD！
![image](https://user-images.githubusercontent.com/128889876/234306627-7ac12ec5-acf3-42cc-a763-0b29b3a20dc0.png)
